name: Stock Frontend Image

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs: 

    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: mr-smithers-excellent/docker-build-push@v6
              name: Build & push Docker image 
              with: 
                image: simonnilsson584/stock-frontend
                tags: latest 
                registry: docker.io
                dockerfile: Dockerfile
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
